---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
labels:
  org.opencontainers.image.title: "Familienkalender"
  org.opencontainers.image.description: "Family dashboard for Home Assistant"
  org.opencontainers.image.source: "https://github.com/elien666/hass-family-calendar"
