name: "Familienkalender"
description: "Unser cooler Kalender mit Dashboard"
version: "next-1"
slug: "family-calendar"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
panel_icon: mdi:calendar-week
panel_admin: false
panel_title: Kalender
homeassistant_api: true
options:
  weather:
    weather_api_key:
    weather_latitude: 53.570
    weather_longitude: 10.091
  hvv:
    geofox_user:
    geofox_secret:
  telegram:
    telegram_bot_token:
    telegram_chat_id:
  garage:
    entity_garage_door:
  laundry:
    entity_washing_machine_new:
    entity_washing_machine_old:
    entity_dryer:
  doorbell:
    entity_doorbell:
    entity_doorbell_button:
  everyday_calendar:
    entity_everyday_calendar:
  physical_buttons:
    buttons_ws_url:
schema:
  weather:
    weather_api_key: str?
    weather_latitude: float?
    weather_longitude: float?
  hvv:
    geofox_user: str?
    geofox_secret: str?
  telegram:
    telegram_bot_token: str?
    telegram_chat_id: str?
  garage:
    entity_garage_door: device
  laundry:
    entity_washing_machine_new: device
    entity_washing_machine_old: device
    entity_dryer: device
  doorbell:
    entity_doorbell: device
    entity_doorbell_button: device
  everyday_calendar:
    entity_everyday_calendar: device
  physical_buttons:
    buttons_ws_url: url?
