name: "Familienkalender"
description: "Unser cooler Kalender mit Dashboard"
version: "1.2"
slug: "family-calendar"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
panel_icon: mdi:calendar-week
panel_admin: false
panel_title: Kalender
homeassistant_api: true
options:
  weather:
    weather_latitude: 53.570
    weather_longitude: 10.091
  garage:
    entity_garage_door: cover.garagentor
  laundry:
    entity_washing_machine_new: input_select.wasching_machine_neu_status
    entity_washing_machine_old: input_select.washing_machine_alt_status
    entity_dryer: input_select.dryer_status
  doorbell:
    entity_doorbell: binary_sensor.tuerklingel_person
    entity_doorbell_button: button.haustur_unlatch_2
  everyday_calendar:
    entity_everyday_calendar: sensor.everyday_calendar
schema:
  weather:
    weather_api_key: str?
    weather_latitude: float?
    weather_longitude: float?
  hvv:
    geofox_user: str?
    geofox_secret: str?
  telegram:
    telegram_bot_token: str?
    telegram_chat_id: str?
  garage:
    entity_garage_door: str?
  laundry:
    entity_washing_machine_new: str?
    entity_washing_machine_old: str?
    entity_dryer: str?
  doorbell:
    entity_doorbell: str?
    entity_doorbell_button: str?
  everyday_calendar:
    entity_everyday_calendar: str?
  physical_buttons:
    buttons_ws_url: url?
